<a href="https://colab.research.google.com/github/mohamedafdailat/TP_IA2/blob/main/TP_IA2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Analyse des données**

**Charger les données et afficher les premières lignes**

In [29]:
import pandas as pd

# Charger le dataset
df = pd.read_csv('maintenance_predictive.csv')

# Afficher les premières lignes
print(df.head())

             Timestamp  Temperature  Vibrations  Pressure  Current  \
0  2024-01-01 00:00:00          NaN        2.58      3.16    11.86   
1  2024-01-01 01:00:00        55.60        2.55      3.35    11.97   
2  2024-01-01 02:00:00        60.74        1.20      3.20    12.06   
3  2024-01-01 03:00:00        66.15        2.67      3.56    12.95   
4  2024-01-01 04:00:00        58.16         NaN      4.10    11.25   

   Operating_Time  Humidity  Noise_Level  Energy_Consumption   Pump_Type  \
0            0.56     67.93        65.62                0.01      Piston   
1            2.04     47.59        70.46                0.01  Centrifuge   
2            3.34     56.45        63.46                0.01      Piston   
3            4.71     43.62        69.28                0.01  Centrifuge   
4            5.90     39.67        67.18                0.01      Piston   

  Location  State  
0   Zone A      0  
1   Zone A      0  
2   Zone A      0  
3   Zone C      0  
4   Zone B      0  


**Identifier les colonnes, types de données et valeurs manquantes**

In [30]:
# Afficher les informations sur les colonnes et les types de données
print(df.info())

# Vérifier les valeurs manquantes
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Timestamp           5000 non-null   object 
 1   Temperature         4750 non-null   float64
 2   Vibrations          4750 non-null   float64
 3   Pressure            4750 non-null   float64
 4   Current             4750 non-null   float64
 5   Operating_Time      5000 non-null   float64
 6   Humidity            4750 non-null   float64
 7   Noise_Level         4750 non-null   float64
 8   Energy_Consumption  4750 non-null   float64
 9   Pump_Type           5000 non-null   object 
 10  Location            5000 non-null   object 
 11  State               5000 non-null   int64  
dtypes: float64(8), int64(1), object(3)
memory usage: 468.9+ KB
None
Timestamp               0
Temperature           250
Vibrations            250
Pressure              250
Current               250
Operatin

**Calculer des statistiques de base**

In [31]:
# Calculer des statistiques de base
print(df.describe())

       Temperature   Vibrations     Pressure      Current  Operating_Time  \
count  4750.000000  4750.000000  4750.000000  4750.000000     5000.000000   
mean     57.254011     3.441402     3.634705    12.343617     2479.450176   
std       9.053411     2.288461     0.762451     1.733788     1428.333659   
min      35.610000    -0.920000     1.810000     8.140000        0.560000   
25%      51.550000     2.350000     3.190000    11.380000     1244.915000   
50%      55.855000     3.040000     3.530000    12.070000     2483.700000   
75%      60.957500     3.800000     3.900000    12.840000     3714.692500   
max      89.970000    14.890000     7.000000    19.990000     4956.740000   

          Humidity  Noise_Level  Energy_Consumption        State  
count  4750.000000  4750.000000         4750.000000  5000.000000  
mean     50.957598    72.306211            0.011158     0.296800  
std      10.669382     8.567884            0.003857     0.775648  
min      15.050000    47.670000       

**Pré-traitement des données**

**Encoder les variables catégoriques**

In [32]:
from sklearn.preprocessing import LabelEncoder

# Encoder les variables catégoriques
label_encoder = LabelEncoder()
df['Pump_Type'] = label_encoder.fit_transform(df['Pump_Type'])
df['Location'] = label_encoder.fit_transform(df['Location'])

In [33]:
df.shape

(5000, 12)

**Gérer les données manquantes**

In [34]:
from sklearn.preprocessing import LabelEncoder

# Encoder les variables catégoriques
label_encoder = LabelEncoder()
df['Pump_Type'] = label_encoder.fit_transform(df['Pump_Type'])
df['Location'] = label_encoder.fit_transform(df['Location'])

# Remplacer les valeurs manquantes par la moyenne des colonnes numériques uniquement
numeric_columns = df.select_dtypes(include=['float64', 'int64']).columns
df[numeric_columns] = df[numeric_columns].fillna(df[numeric_columns].mean())

# Afficher les premières lignes pour vérifier
print(df.head())

             Timestamp  Temperature  Vibrations  Pressure  Current  \
0  2024-01-01 00:00:00    57.254011    2.580000      3.16    11.86   
1  2024-01-01 01:00:00    55.600000    2.550000      3.35    11.97   
2  2024-01-01 02:00:00    60.740000    1.200000      3.20    12.06   
3  2024-01-01 03:00:00    66.150000    2.670000      3.56    12.95   
4  2024-01-01 04:00:00    58.160000    3.441402      4.10    11.25   

   Operating_Time  Humidity  Noise_Level  Energy_Consumption  Pump_Type  \
0            0.56     67.93        65.62                0.01          2   
1            2.04     47.59        70.46                0.01          0   
2            3.34     56.45        63.46                0.01          2   
3            4.71     43.62        69.28                0.01          0   
4            5.90     39.67        67.18                0.01          2   

   Location  State  
0         0      0  
1         0      0  
2         0      0  
3         2      0  
4         1      0  


**Convertir la colonne Timestamp en datetime**

In [35]:
# Convertir la colonne Timestamp en datetime
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

# Trier les données par Timestamp
df.sort_values('Timestamp', inplace=True)

**Normaliser ou standardiser les variables numériques**

In [36]:
from sklearn.preprocessing import StandardScaler

# Normaliser les variables numériques
scaler = StandardScaler()
numerical_columns = ['Temperature', 'Vibrations', 'Pressure', 'Current', 'Operating_Time', 'Humidity', 'Noise_Level', 'Energy_Consumption']
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

**Créer les vecteurs X et Y**

In [37]:
# Créer les vecteurs X et Y
X = df.drop(columns=['State', 'Timestamp'])
Y = df['State']

**Créer des séquences temporelles**

In [38]:
import numpy as np

def create_sequences(data, target, window_size):
    X_seq, Y_seq = [], []
    for i in range(len(data) - window_size):
        X_seq.append(data[i:i+window_size])
        Y_seq.append(target[i+window_size])
    return np.array(X_seq), np.array(Y_seq)

window_size = 10
X_seq, Y_seq = create_sequences(X.values, Y.values, window_size)

# Vérifier la taille des séquences
print(X_seq.shape, Y_seq.shape)

(4990, 10, 10) (4990,)


**Diviser les données en ensembles d'entraînement et de test**

In [39]:
from sklearn.model_selection import train_test_split

# Diviser les données
X_train, X_test, Y_train, Y_test = train_test_split(X_seq, Y_seq, test_size=0.3, random_state=42)

In [40]:
# ré-afficher les premières lignes
print(df.head(10))

            Timestamp   Temperature  Vibrations  Pressure   Current  \
0 2024-01-01 00:00:00  8.053077e-16   -0.386230 -0.638846 -0.286213   
1 2024-01-01 01:00:00 -1.874606e-01   -0.399682 -0.383149 -0.221113   
2 2024-01-01 02:00:00  3.950915e-01   -1.004987 -0.585015 -0.167849   
3 2024-01-01 03:00:00  1.008245e+00   -0.345877 -0.100536  0.358868   
4 2024-01-01 04:00:00  1.026821e-01    0.000000  0.626181 -0.647222   
5 2024-01-01 05:00:00  1.593506e-01   -0.767348 -0.706134 -0.706404   
6 2024-01-01 06:00:00  1.206584e+00    0.272880  0.000000  0.530495   
7 2024-01-01 07:00:00  8.053077e-16    0.021790 -0.706134 -0.475595   
8 2024-01-01 08:00:00 -3.105553e-02   -0.525226 -0.746507 -0.949049   
9 2024-01-01 09:00:00  4.528934e-01   -0.260686  0.370484 -0.493349   

   Operating_Time  Humidity  Noise_Level  Energy_Consumption  Pump_Type  \
0       -1.735686  1.632255    -0.800738           -0.308074          2   
1       -1.734649 -0.323866    -0.221101           -0.308074        

**Apprentissage, construction du modèle, archivage et gestion des expériences avec WandB**

**Développer un modèle LSTM**

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Input

# Construire le modèle LSTM
model = Sequential()
model.add(Input(shape=(X_train.shape[1], X_train.shape[2])))  # Ajouter une couche Input
model.add(LSTM(50))
model.add(Dense(4, activation='softmax'))  # 4 classes pour l'état de la pompe

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Afficher le résumé du modèle
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_8 (LSTM)                        │ (None, 50)                  │          12,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 4)                   │             204 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 12,404 (48.45 KB)

 Trainable params: 12,404 (48.45 KB)

 Non-trainable params: 0 (0.00 B)

**Tester plusieurs jeux d'hyperparamètres**

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import numpy as np

# Définir les hyperparamètres à tester
units_list = [30, 50, 100]  # Nombre de neurones dans la couche LSTM
optimizer_list = ['adam', 'rmsprop']  # Optimiseurs à tester
batch_size_list = [32, 64]  # Taille des lots
epochs_list = [10, 20]  # Nombre d'époques

best_accuracy = 0
best_params = {}

# Boucle pour tester les hyperparamètres
for units in units_list:
    for optimizer in optimizer_list:
        for batch_size in batch_size_list:
            for epochs in epochs_list:
                print(f"Test des paramètres: units={units}, optimizer={optimizer}, batch_size={batch_size}, epochs={epochs}")

                # Créer et entraîner le modèle
                model = Sequential()
                model.add(LSTM(units, input_shape=(X_train.shape[1], X_train.shape[2])))
                model.add(Dense(4, activation='softmax'))
                model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])
                model.fit(X_train, Y_train, epochs=epochs, batch_size=batch_size, verbose=0)

                # Évaluer le modèle
                _, accuracy = model.evaluate(X_test, Y_test, verbose=0)
                print(f"Accuracy: {accuracy}")

                # Mettre à jour les meilleurs paramètres
                if accuracy > best_accuracy:
                    best_accuracy = accuracy
                    best_params = {
                        'units': units,
                        'optimizer': optimizer,
                        'batch_size': batch_size,
                        'epochs': epochs
                    }

# Afficher les meilleurs résultats
print(f"Meilleure précision: {best_accuracy} avec les paramètres {best_params}")

Test des paramètres: units=30, optimizer=adam, batch_size=32, epochs=10


/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Accuracy: 0.8557114005088806
Test des paramètres: units=30, optimizer=adam, batch_size=32, epochs=20
Accuracy: 0.8557114005088806
Test des paramètres: units=30, optimizer=adam, batch_size=64, epochs=10
Accuracy: 0.8557114005088806
Test des paramètres: units=30, optimizer=adam, batch_size=64, epochs=20
Accuracy: 0.8557114005088806
Test des paramètres: units=30, optimizer=rmsprop, batch_size=32, epochs=10
Accuracy: 0.8557114005088806
Test des paramètres: units=30, optimizer=rmsprop, batch_size=32, epochs=20
Accuracy: 0.8557114005088806
Test des paramètres: units=30, optimizer=rmsprop, batch_size=64, epochs=10
Accuracy: 0.8557114005088806
Test des paramètres: units=30, optimizer=rmsprop, batch_size=64, epochs=20
Accuracy: 0.8557114005088806
Test des paramètres: units=50, optimizer=adam, batch_size=32, epochs=10
Accuracy: 0.8557114005088806
Test des paramètres: units=50, optimizer=adam, batch_size=32, epochs=20
Accuracy: 0.8557114005088806
Test des paramètres: units=50, optimizer=adam, bat

**Tester d'autres modèles ML sans considérer la composante temporelle**

In [42]:
# Aplatir les séquences temporelles pour les modèles classiques
X_train_flat = X_train.reshape(X_train.shape[0], -1)  # Forme : (n_samples, n_features * window_size)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

**Exemple avec Random Forest**

In [43]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Entraîner un modèle Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_flat, Y_train)

# Évaluer le modèle
Y_pred_rf = rf_model.predict(X_test_flat)
accuracy_rf = accuracy_score(Y_test, Y_pred_rf)
precision_rf = precision_score(Y_test, Y_pred_rf, average='weighted')
recall_rf = recall_score(Y_test, Y_pred_rf, average='weighted')
conf_matrix_rf = confusion_matrix(Y_test, Y_pred_rf)

print("Random Forest - Accuracy:", accuracy_rf)
print("Random Forest - Precision:", precision_rf)
print("Random Forest - Recall:", recall_rf)
print("Random Forest - Matrice de confusion:\n", conf_matrix_rf)

Random Forest - Accuracy: 0.8557114228456913
Random Forest - Precision: 0.7322420391885976
Random Forest - Recall: 0.8557114228456913
Random Forest - Matrice de confusion:
 [[1281    0    0    0]
 [  63    0    0    0]
 [  67    0    0    0]
 [  86    0    0    0]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


**Exemple avec SVM**

In [44]:
from sklearn.svm import SVC

# Entraîner un modèle SVM
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train_flat, Y_train)

# Évaluer le modèle
Y_pred_svm = svm_model.predict(X_test_flat)
accuracy_svm = accuracy_score(Y_test, Y_pred_svm)
precision_svm = precision_score(Y_test, Y_pred_svm, average='weighted')
recall_svm = recall_score(Y_test, Y_pred_svm, average='weighted')
conf_matrix_svm = confusion_matrix(Y_test, Y_pred_svm)

print("SVM - Accuracy:", accuracy_svm)
print("SVM - Precision:", precision_svm)
print("SVM - Recall:", recall_svm)
print("SVM - Matrice de confusion:\n", conf_matrix_svm)

SVM - Accuracy: 0.8557114228456913
SVM - Precision: 0.7322420391885976
SVM - Recall: 0.8557114228456913
SVM - Matrice de confusion:
 [[1281    0    0    0]
 [  63    0    0    0]
 [  67    0    0    0]
 [  86    0    0    0]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


**Tracer l'apprentissage avec Weights and Biases**

In [57]:
import wandb
from wandb.integration.keras import WandbCallback # Import WandbCallback from the correct submodule
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [60]:
import wandb
from wandb.integration.keras import WandbCallback # Import WandbCallback from the correct submodule
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import numpy as np

# Initialiser Weights and Biases
wandb.init(project="maintenance-predictive", config={
    "units": 50,
    "optimizer": "adam",
    "batch_size": 32,
    "epochs": 20,
    "window_size": 10
})

# Construire le modèle LSTM
model = Sequential()
model.add(LSTM(wandb.config.units, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dense(4, activation='softmax'))
model.compile(optimizer=wandb.config.optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Entraîner le modèle avec WandB
# Disable graph saving explicitly using save_graph=False
history = model.fit(
    X_train, Y_train,
    epochs=wandb.config.epochs,
    batch_size=wandb.config.batch_size,
    validation_data=(X_test, Y_test),
    callbacks=[WandbCallback(save_model=False, save_graph=False)]
)


# Enregistrer le modèle
model.save("lstm_model.h5")
wandb.save("lstm_model.h5") # wandb.save is used to upload the model to wandb

# Terminer la session WandB
wandb.finish()

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


110/110 ━━━━━━━━━━━━━━━━━━━━ 8s 28ms/step - accuracy: 0.7430 - loss: 0.8636 - val_accuracy: 0.8557 - val_loss: 0.5816
Epoch 2/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.8471 - loss: 0.5977 - val_accuracy: 0.8557 - val_loss: 0.5798
Epoch 3/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.8514 - loss: 0.5813 - val_accuracy: 0.8557 - val_loss: 0.5802
Epoch 4/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.8478 - loss: 0.5900 - val_accuracy: 0.8557 - val_loss: 0.5783
Epoch 5/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.8538 - loss: 0.5707 - val_accuracy: 0.8557 - val_loss: 0.5797
Epoch 6/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - accuracy: 0.8374 - loss: 0.6094 - val_accuracy: 0.8557 - val_loss: 0.5780
Epoch 7/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.8321 - loss: 0.6280 - val_accuracy: 0.8557 - val_loss: 0.5845
Epoch 8/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8427 - loss: 0.6006 - val_accuracy: 0.8557

**Archiver les modèles testés dans Weights and Biases**

In [62]:
import wandb
from wandb.integration.keras import WandbCallback # Import WandbCallback from the correct submodule
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Initialiser Weights and Biases
wandb.init(project="maintenance-predictive", config={
    "units": 50,
    "optimizer": "adam",
    "batch_size": 32,
    "epochs": 20,
    "window_size": 10
})

# Construire le modèle LSTM complexe
model = Sequential()

# Première couche LSTM avec retour des séquences pour empiler une deuxième couche LSTM
model.add(LSTM(
    wandb.config.units,  # Nombre de neurones dans la couche LSTM
    input_shape=(X_train.shape[1], X_train.shape[2]),  # Forme d'entrée
    return_sequences=True  # Retourne une séquence pour la couche suivante
))

# Ajouter une couche Dropout pour la régularisation
model.add(Dropout(0.2))  # Désactive 20 % des neurones pendant l'entraînement

# Deuxième couche LSTM
model.add(LSTM(
    wandb.config.units // 2,  # Moitié de neurones par rapport à la première couche
    return_sequences=False  # Ne retourne pas de séquence (dernière couche LSTM)
))

# Ajouter une couche Dense intermédiaire
model.add(Dense(64, activation='relu'))  # 64 neurones avec activation ReLU

# Ajouter une autre couche Dropout
model.add(Dropout(0.2))

# Couche de sortie
model.add(Dense(4, activation='softmax'))  # 4 classes pour l'état de la pompe

# Compiler le modèle
model.compile(
    optimizer=wandb.config.optimizer,  # Optimiseur configuré dans WandB
    loss='sparse_categorical_crossentropy',  # Fonction de perte
    metrics=['accuracy']  # Métrique à surveiller
)

# Afficher le résumé du modèle
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_18 (LSTM)                       │ (None, 10, 50)              │          12,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_6 (Dropout)                  │ (None, 10, 50)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_19 (LSTM)                       │ (None, 25)                  │           7,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 64)                  │           1,664 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_7 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 4)                   │             260 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21,724 (84.86 KB)

 Trainable params: 21,724 (84.86 KB)

 Non-trainable params: 0 (0.00 B)

In [64]:
# Entraîner le modèle avec WandB
history = model.fit(
    X_train, Y_train,
    epochs=wandb.config.epochs,
    batch_size=wandb.config.batch_size,
    validation_data=(X_test, Y_test),
    callbacks=[WandbCallback(save_model=False, save_graph=False)]  # Disable graph saving
)

# Enregistrer le modèle
model.save("lstm_complex_model.h5")
wandb.save("lstm_complex_model.h5")

# Terminer la session WandB
wandb.finish()

Epoch 1/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - accuracy: 0.8446 - loss: 0.8190 - val_accuracy: 0.8557 - val_loss: 0.5762
Epoch 2/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.8443 - loss: 0.6176 - val_accuracy: 0.8557 - val_loss: 0.5909
Epoch 3/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.8570 - loss: 0.5717 - val_accuracy: 0.8557 - val_loss: 0.5730
Epoch 4/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8563 - loss: 0.5778 - val_accuracy: 0.8557 - val_loss: 0.5786
Epoch 5/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8466 - loss: 0.6047 - val_accuracy: 0.8557 - val_loss: 0.5748
Epoch 6/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8479 - loss: 0.5972 - val_accuracy: 0.8557 - val_loss: 0.5746
Epoch 7/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8474 - loss: 0.5996 - val_accuracy: 0.8557 - val_loss: 0.5774
Epoch 8/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8433 - loss: 0.6117 - val_accu

**Evaluation**

**Evaluer les modèles**

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Prédire sur l'ensemble de test
Y_pred = model.predict(X_test)
Y_pred_classes = np.argmax(Y_pred, axis=1)

# Calculer les métriques
conf_matrix = confusion_matrix(Y_test, Y_pred_classes)
accuracy = accuracy_score(Y_test, Y_pred_classes)
precision = precision_score(Y_test, Y_pred_classes, average='weighted')
recall = recall_score(Y_test, Y_pred_classes, average='weighted')

print("Confusion Matrix:\n", conf_matrix)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
Confusion Matrix:
 [[1281    0    0    0]
 [  63    0    0    0]
 [  67    0    0    0]
 [  86    0    0    0]]
Accuracy: 0.8557114228456913
Precision: 0.7322420391885976
Recall: 0.8557114228456913


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [67]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Modèle LSTM plus complexe
model = Sequential()

# Première couche LSTM avec retour des séquences pour empiler une deuxième couche LSTM
model.add(LSTM(
    units=64,  # Nombre de neurones dans la couche LSTM
    input_shape=(X_train.shape[1], X_train.shape[2]),  # Forme d'entrée
    return_sequences=True  # Retourne une séquence pour la couche suivante
))

# Ajouter une couche Dropout pour la régularisation
model.add(Dropout(0.2))  # Désactive 20 % des neurones pendant l'entraînement

# Deuxième couche LSTM
model.add(LSTM(
    units=32,  # Moitié de neurones par rapport à la première couche
    return_sequences=False  # Ne retourne pas de séquence (dernière couche LSTM)
))

# Ajouter une couche Dense intermédiaire
model.add(Dense(64, activation='relu'))  # 64 neurones avec activation ReLU

# Ajouter une autre couche Dropout
model.add(Dropout(0.2))

# Couche de sortie
model.add(Dense(4, activation='softmax'))  # 4 classes pour l'état de la pompe

# Compiler le modèle
model.compile(
    optimizer='adam',  # Optimiseur
    loss='sparse_categorical_crossentropy',  # Fonction de perte
    metrics=['accuracy']  # Métrique à surveiller
)

# Afficher le résumé du modèle
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm_20 (LSTM)                       │ (None, 10, 64)              │          19,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_8 (Dropout)                  │ (None, 10, 64)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_21 (LSTM)                       │ (None, 32)                  │          12,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 64)                  │           2,112 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_9 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_20 (Dense)                     │ (None, 4)                   │             260 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 33,988 (132.77 KB)

 Trainable params: 33,988 (132.77 KB)

 Non-trainable params: 0 (0.00 B)

In [70]:
import wandb
from wandb.integration.keras import WandbCallback # Import WandbCallback from the correct submodule
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

# Initialiser Weights and Biases
wandb.init(project="maintenance-predictive", config={
    "units": 50,
    "optimizer": "adam",
    "batch_size": 32,
    "epochs": 20,
    "window_size": 10
})


# Entraîner le modèle avec WandB
history = model.fit(
    X_train, Y_train,
    # Access the config values after wandb.init()
    epochs=wandb.config.epochs,
    batch_size=wandb.config.batch_size,
    validation_data=(X_test, Y_test),
    callbacks=[WandbCallback(save_model=False, save_graph=False)]  # Disable graph saving
)

# Enregistrer le modèle
model.save("lstm_complex_model.h5")
wandb.save("lstm_complex_model.h5")

# Terminer la session WandB
wandb.finish()

Epoch 1/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.8141 - loss: 0.8301 - val_accuracy: 0.8557 - val_loss: 0.5824
Epoch 2/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.8571 - loss: 0.5741 - val_accuracy: 0.8557 - val_loss: 0.5742
Epoch 3/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.8461 - loss: 0.6085 - val_accuracy: 0.8557 - val_loss: 0.5724
Epoch 4/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8554 - loss: 0.5811 - val_accuracy: 0.8557 - val_loss: 0.5743
Epoch 5/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8481 - loss: 0.6021 - val_accuracy: 0.8557 - val_loss: 0.5749
Epoch 6/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8399 - loss: 0.6267 - val_accuracy: 0.8557 - val_loss: 0.5765
Epoch 7/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8505 - loss: 0.5942 - val_accuracy: 0.8557 - val_loss: 0.5772
Epoch 8/20
110/110 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.8460 - loss: 0.6044 - val_accu

**Archivage des modèles**

In [65]:
# Sauvegarder le modèle Random Forest
import joblib
joblib.dump(rf_model, 'random_forest_model.pkl')

# Initialiser une nouvelle session WandB pour l'archivage
wandb.init(project="maintenance-predictive", job_type="model_archiving")

# Archiver dans WandB
wandb.save('random_forest_model.pkl')

# Terminer la session WandB d'archivage
wandb.finish()

**Intégration applicative**

**Intégrer le modèle dans une API Flask**

In [66]:
from flask import Flask, request, jsonify
import tensorflow as tf
import numpy as np

app = Flask(__name__)

# Charger le modèle
model = tf.keras.models.load_model('lstm_model.h5')

@app.route('/predict', methods=['POST'])
def predict():
    # Récupérer les données de la requête POST
    data = request.json.get('data')

    # Convertir les données en un tableau numpy
    data = np.array(data)

    # Vérifier que les données ont la bonne forme (10 pas de temps, 10 caractéristiques)
    if data.shape != (10, 10):
        return jsonify({"error": "Les données doivent avoir la forme (10, 10)"}), 400

    # Redimensionner les données pour correspondre à l'entrée du modèle (1, 10, 10)
    data = data.reshape(1, 10, 10)

    # Faire la prédiction
    prediction = model.predict(data)
    predicted_class = np.argmax(prediction, axis=1)

    # Retourner la prédiction
    return jsonify({"predicted_state": int(predicted_class[0])})

if __name__ == '__main__':
    app.run(debug=True)

 * Serving Flask app '__main__'
 * Debug mode: on


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat
